-- MySQL Script generated by MySQL Workbench
-- Thu Apr 19 14:51:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecommerce` ;

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Ecommerce`.`category_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`category_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`category_t` (
  `category_id` INT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  `category_description` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`products_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`products_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`products_t` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_description` VARCHAR(80) NULL,
  `product_price` FLOAT NULL,
  `product_discount` FLOAT NULL,
  `product_weight` FLOAT NULL,
  `product_height` FLOAT NULL,
  `product_width` FLOAT NULL,
  `category_t_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_t_category_id`),
  INDEX `fk_products_t_category_t_idx` (`category_t_category_id` ASC),
  CONSTRAINT `fk_products_t_category_t`
    FOREIGN KEY (`category_t_category_id`)
    REFERENCES `Ecommerce`.`category_t` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`vendor_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`vendor_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`vendor_t` (
  `vendor_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(45) NULL,
  `vendor_phone` VARCHAR(45) NULL,
  `vendor_email` VARCHAR(45) NULL,
  `vendor_address` VARCHAR(45) NULL,
  PRIMARY KEY (`vendor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`branches_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`branches_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`branches_t` (
  `branch_id` INT NOT NULL,
  `branch_address` VARCHAR(45) NULL,
  `branch_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`vendor_t_has_products_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`vendor_t_has_products_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`vendor_t_has_products_t` (
  `vendor_t_vendor_id` INT NOT NULL,
  `products_t_product_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `product_price` FLOAT NULL,
  `product_amount` INT NULL,
  `updated_time` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`vendor_t_vendor_id`, `products_t_product_id`, `branch_id`, `updated_time`),
  INDEX `fk_vendor_t_has_products_t_products_t1_idx` (`products_t_product_id` ASC),
  INDEX `fk_vendor_t_has_products_t_vendor_t1_idx` (`vendor_t_vendor_id` ASC),
  INDEX `fk_vendor_t_has_products_t_branches_t1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_vendor_t_has_products_t_vendor_t1`
    FOREIGN KEY (`vendor_t_vendor_id`)
    REFERENCES `Ecommerce`.`vendor_t` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendor_t_has_products_t_products_t1`
    FOREIGN KEY (`products_t_product_id`)
    REFERENCES `Ecommerce`.`products_t` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendor_t_has_products_t_branches_t1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Ecommerce`.`branches_t` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`branches_t_has_products_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`branches_t_has_products_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`branches_t_has_products_t` (
  `branches_t_branch_id` INT NOT NULL,
  `products_t_product_id` INT NOT NULL,
  PRIMARY KEY (`branches_t_branch_id`, `products_t_product_id`),
  INDEX `fk_branches_t_has_products_t_products_t1_idx` (`products_t_product_id` ASC),
  INDEX `fk_branches_t_has_products_t_branches_t1_idx` (`branches_t_branch_id` ASC),
  CONSTRAINT `fk_branches_t_has_products_t_branches_t1`
    FOREIGN KEY (`branches_t_branch_id`)
    REFERENCES `Ecommerce`.`branches_t` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branches_t_has_products_t_products_t1`
    FOREIGN KEY (`products_t_product_id`)
    REFERENCES `Ecommerce`.`products_t` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`employees_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`employees_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`employees_t` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NULL,
  `employee_phone` VARCHAR(45) NULL,
  `employee_salary` FLOAT NULL,
  `employee_supervisor_id` INT NULL,
  `branches_t_branch_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `branches_t_branch_id`),
  INDEX `fk_employees_t_employees_t1_idx` (`employee_supervisor_id` ASC),
  INDEX `fk_employees_t_branches_t1_idx` (`branches_t_branch_id` ASC),
  CONSTRAINT `fk_employees_t_employees_t1`
    FOREIGN KEY (`employee_supervisor_id`)
    REFERENCES `Ecommerce`.`employees_t` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_t_branches_t1`
    FOREIGN KEY (`branches_t_branch_id`)
    REFERENCES `Ecommerce`.`branches_t` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`skills_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`skills_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`skills_t` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `skills_name` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`skills_t_has_employees_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`skills_t_has_employees_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`skills_t_has_employees_t` (
  `skills_t_skill_id` INT NOT NULL,
  `employees_t_employee_id` INT NOT NULL,
  PRIMARY KEY (`skills_t_skill_id`, `employees_t_employee_id`),
  INDEX `fk_skills_t_has_employees_t_employees_t1_idx` (`employees_t_employee_id` ASC),
  INDEX `fk_skills_t_has_employees_t_skills_t1_idx` (`skills_t_skill_id` ASC),
  CONSTRAINT `fk_skills_t_has_employees_t_skills_t1`
    FOREIGN KEY (`skills_t_skill_id`)
    REFERENCES `Ecommerce`.`skills_t` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_t_has_employees_t_employees_t1`
    FOREIGN KEY (`employees_t_employee_id`)
    REFERENCES `Ecommerce`.`employees_t` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`orders_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`orders_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`orders_t` (
  `idorder_id` INT NOT NULL,
  `order_date` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idorder_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`order_lines_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`order_lines_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`order_lines_t` (
  `orders_t_idorder_id` INT NOT NULL,
  `products_t_product_id` INT NOT NULL,
  PRIMARY KEY (`orders_t_idorder_id`, `products_t_product_id`),
  INDEX `fk_orders_t_has_products_t_products_t1_idx` (`products_t_product_id` ASC),
  INDEX `fk_orders_t_has_products_t_orders_t1_idx` (`orders_t_idorder_id` ASC),
  CONSTRAINT `fk_orders_t_has_products_t_orders_t1`
    FOREIGN KEY (`orders_t_idorder_id`)
    REFERENCES `Ecommerce`.`orders_t` (`idorder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_t_has_products_t_products_t1`
    FOREIGN KEY (`products_t_product_id`)
    REFERENCES `Ecommerce`.`products_t` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`custmers_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`custmers_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`custmers_t` (
  `custmer_id` INT NOT NULL,
  `custmer_name` VARCHAR(45) NULL,
  `custmer_phone` VARCHAR(45) NULL,
  `custmer_email` VARCHAR(45) NULL,
  `custmer_address` VARCHAR(45) NULL,
  `custmer_postalcode` VARCHAR(45) NULL,
  `custmers_subscriber` BIT(1) NULL,
  PRIMARY KEY (`custmer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`custmers_t_has_orders_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`custmers_t_has_orders_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`custmers_t_has_orders_t` (
  `custmers_t_custmer_id` INT NOT NULL,
  `orders_t_idorder_id` INT NOT NULL,
  PRIMARY KEY (`custmers_t_custmer_id`, `orders_t_idorder_id`),
  INDEX `fk_custmers_t_has_orders_t_orders_t1_idx` (`orders_t_idorder_id` ASC),
  INDEX `fk_custmers_t_has_orders_t_custmers_t1_idx` (`custmers_t_custmer_id` ASC),
  CONSTRAINT `fk_custmers_t_has_orders_t_custmers_t1`
    FOREIGN KEY (`custmers_t_custmer_id`)
    REFERENCES `Ecommerce`.`custmers_t` (`custmer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custmers_t_has_orders_t_orders_t1`
    FOREIGN KEY (`orders_t_idorder_id`)
    REFERENCES `Ecommerce`.`orders_t` (`idorder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`complaint_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`complaint_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`complaint_t` (
  `complaint_id` INT NOT NULL,
  `complaint_description` VARCHAR(80) NULL,
  `complaint_code` VARCHAR(45) NULL,
  `complaint_time` DATETIME(6) NULL,
  `custmers_t_custmer_id` INT NOT NULL,
  PRIMARY KEY (`complaint_id`, `custmers_t_custmer_id`),
  INDEX `fk_complaint_t_custmers_t1_idx` (`custmers_t_custmer_id` ASC),
  CONSTRAINT `fk_complaint_t_custmers_t1`
    FOREIGN KEY (`custmers_t_custmer_id`)
    REFERENCES `Ecommerce`.`custmers_t` (`custmer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`payment_mehtod_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`payment_mehtod_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`payment_mehtod_t` (
  `payment_mehtod_id` INT NOT NULL,
  `payment_mehtod_name` VARCHAR(45) NULL,
  PRIMARY KEY (`payment_mehtod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`receipt_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`receipt_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`receipt_t` (
  `receipt_id` INT NOT NULL,
  `receipt_totalprice` VARCHAR(45) NULL,
  `orders_t_idorder_id` INT NOT NULL,
  `payment_mehtod_t_payment_mehtod_id` INT NOT NULL,
  PRIMARY KEY (`receipt_id`, `orders_t_idorder_id`, `payment_mehtod_t_payment_mehtod_id`),
  INDEX `fk_receipt_t_orders_t1_idx` (`orders_t_idorder_id` ASC),
  INDEX `fk_receipt_t_payment_mehtod_t1_idx` (`payment_mehtod_t_payment_mehtod_id` ASC),
  CONSTRAINT `fk_receipt_t_orders_t1`
    FOREIGN KEY (`orders_t_idorder_id`)
    REFERENCES `Ecommerce`.`orders_t` (`idorder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_t_payment_mehtod_t1`
    FOREIGN KEY (`payment_mehtod_t_payment_mehtod_id`)
    REFERENCES `Ecommerce`.`payment_mehtod_t` (`payment_mehtod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`shipment_company_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`shipment_company_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`shipment_company_t` (
  `shipment_company_id` INT NOT NULL,
  `shipment_company_name` VARCHAR(45) NULL,
  `shipment_company_phone` VARCHAR(45) NULL,
  `shipment_company_fax` VARCHAR(45) NULL,
  `shipment_company_email` VARCHAR(45) NULL,
  `shipment_company_address` VARCHAR(45) NULL,
  PRIMARY KEY (`shipment_company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`zones_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`zones_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`zones_t` (
  `zone_id` INT NOT NULL AUTO_INCREMENT,
  `zone_name` VARCHAR(45) NULL,
  PRIMARY KEY (`zone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`shipments_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`shipments_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`shipments_t` (
  `shipment_id` INT NOT NULL AUTO_INCREMENT,
  `shipment_source` INT NOT NULL,
  `shipment_destination` INT NOT NULL,
  `shipment_weight` VARCHAR(45) NULL,
  `shipment_price` VARCHAR(45) NULL,
  `orders_t_idorder_id` INT NOT NULL,
  `shipment_company_t_shipment_company_id` INT NOT NULL,
  PRIMARY KEY (`shipment_id`, `shipment_source`, `shipment_destination`, `orders_t_idorder_id`, `shipment_company_t_shipment_company_id`),
  INDEX `fk_shipments_t_zones_t1_idx` (`shipment_source` ASC),
  INDEX `fk_shipments_t_zones_t2_idx` (`shipment_destination` ASC),
  INDEX `fk_shipments_t_shipment_company_t1_idx` (`shipment_company_t_shipment_company_id` ASC),
  INDEX `fk_shipments_t_orders_t1_idx` (`orders_t_idorder_id` ASC),
  CONSTRAINT `fk_shipments_t_zones_t1`
    FOREIGN KEY (`shipment_source`)
    REFERENCES `Ecommerce`.`zones_t` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipments_t_zones_t2`
    FOREIGN KEY (`shipment_destination`)
    REFERENCES `Ecommerce`.`zones_t` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipments_t_shipment_company_t1`
    FOREIGN KEY (`shipment_company_t_shipment_company_id`)
    REFERENCES `Ecommerce`.`shipment_company_t` (`shipment_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipments_t_orders_t1`
    FOREIGN KEY (`orders_t_idorder_id`)
    REFERENCES `Ecommerce`.`orders_t` (`idorder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`cities_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`cities_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`cities_t` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NULL,
  `zones_t_zone_id` INT NOT NULL,
  PRIMARY KEY (`city_id`, `zones_t_zone_id`),
  INDEX `fk_cities_t_zones_t1_idx` (`zones_t_zone_id` ASC),
  CONSTRAINT `fk_cities_t_zones_t1`
    FOREIGN KEY (`zones_t_zone_id`)
    REFERENCES `Ecommerce`.`zones_t` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`shipping_rates_t`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`shipping_rates_t` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`shipping_rates_t` (
  `shipment_company_t_shipment_company_id` INT NOT NULL,
  `zone_source` INT NOT NULL,
  `zones_destination` INT NOT NULL,
  `shipping_unit` FLOAT NULL,
  `shipping_rate` FLOAT NULL,
  `isFirst` BIT(1) NULL,
  `shipping_rates_tcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shipment_company_t_shipment_company_id`, `zone_source`, `zones_destination`, `shipping_rates_tcol`),
  INDEX `fk_zones_t_has_shipment_company_t_shipment_company_t1_idx` (`shipment_company_t_shipment_company_id` ASC),
  INDEX `fk_zones_t_has_shipment_company_t_zones_t1_idx` (`zone_source` ASC),
  INDEX `fk_shipping_rates_t_zones_t1_idx` (`zones_destination` ASC),
  CONSTRAINT `fk_zones_t_has_shipment_company_t_zones_t1`
    FOREIGN KEY (`zone_source`)
    REFERENCES `Ecommerce`.`zones_t` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zones_t_has_shipment_company_t_shipment_company_t1`
    FOREIGN KEY (`shipment_company_t_shipment_company_id`)
    REFERENCES `Ecommerce`.`shipment_company_t` (`shipment_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping_rates_t_zones_t1`
    FOREIGN KEY (`zones_destination`)
    REFERENCES `Ecommerce`.`zones_t` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
